-- Egyptian Governorates (27)
INSERT INTO governorates (id, name_en, name_ar) VALUES (1, 'Cairo', 'القاهرة');
INSERT INTO governorates (id, name_en, name_ar) VALUES (2, 'Giza', 'الجيزة');
INSERT INTO governorates (id, name_en, name_ar) VALUES (3, 'Alexandria', 'الأسكندرية');
INSERT INTO governorates (id, name_en, name_ar) VALUES (4, 'Dakahlia', 'الدقهلية');
INSERT INTO governorates (id, name_en, name_ar) VALUES (5, 'Red Sea', 'البحر الأحمر');
INSERT INTO governorates (id, name_en, name_ar) VALUES (6, 'Beheira', 'البحيرة');
INSERT INTO governorates (id, name_en, name_ar) VALUES (7, 'Fayoum', 'الفيوم');
INSERT INTO governorates (id, name_en, name_ar) VALUES (8, 'Gharbiya', 'الغربية');
INSERT INTO governorates (id, name_en, name_ar) VALUES (9, 'Ismailia', 'الإسماعلية');
INSERT INTO governorates (id, name_en, name_ar) VALUES (10, 'Menofia', 'المنوفية');
INSERT INTO governorates (id, name_en, name_ar) VALUES (11, 'Minya', 'المنيا');
INSERT INTO governorates (id, name_en, name_ar) VALUES (12, 'Qaliubiya', 'القليوبية');
INSERT INTO governorates (id, name_en, name_ar) VALUES (13, 'New Valley', 'الوادي الجديد');
INSERT INTO governorates (id, name_en, name_ar) VALUES (14, 'Suez', 'السويس');
INSERT INTO governorates (id, name_en, name_ar) VALUES (15, 'Aswan', 'اسوان');
INSERT INTO governorates (id, name_en, name_ar) VALUES (16, 'Assiut', 'اسيوط');
INSERT INTO governorates (id, name_en, name_ar) VALUES (17, 'Beni Suef', 'بني سويف');
INSERT INTO governorates (id, name_en, name_ar) VALUES (18, 'Port Said', 'بورسعيد');
INSERT INTO governorates (id, name_en, name_ar) VALUES (19, 'Damietta', 'دمياط');
INSERT INTO governorates (id, name_en, name_ar) VALUES (20, 'Sharkia', 'الشرقية');
INSERT INTO governorates (id, name_en, name_ar) VALUES (21, 'South Sinai', 'جنوب سيناء');
INSERT INTO governorates (id, name_en, name_ar) VALUES (22, 'Kafr Al sheikh', 'كفر الشيخ');
INSERT INTO governorates (id, name_en, name_ar) VALUES (23, 'Matrouh', 'مطروح');
INSERT INTO governorates (id, name_en, name_ar) VALUES (24, 'Luxor', 'الأقصر');
INSERT INTO governorates (id, name_en, name_ar) VALUES (25, 'Qena', 'قنا');
INSERT INTO governorates (id, name_en, name_ar) VALUES (26, 'North Sinai', 'شمال سيناء');
INSERT INTO governorates (id, name_en, name_ar) VALUES (27, 'Sohag', 'سوهاج');

-- Egyptian Cities (396)
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (1, 1, '15 May', '15 مايو');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (2, 1, 'Al Azbakeyah', 'الازبكية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (3, 1, 'Al Basatin', 'البساتين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (4, 1, 'Tebin', 'التبين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (5, 1, 'El-Khalifa', 'الخليفة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (6, 1, 'El darrasa', 'الدراسة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (7, 1, 'Aldarb Alahmar', 'الدرب الاحمر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (8, 1, 'Zawya al-Hamra', 'الزاوية الحمراء');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (9, 1, 'El-Zaytoun', 'الزيتون');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (10, 1, 'Sahel', 'الساحل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (11, 1, 'El Salam', 'السلام');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (12, 1, 'Sayeda Zeinab', 'السيدة زينب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (13, 1, 'El Sharabeya', 'الشرابية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (14, 1, 'Shorouk', 'مدينة الشروق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (15, 1, 'El Daher', 'الظاهر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (16, 1, 'Ataba', 'العتبة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (17, 1, 'New Cairo', 'القاهرة الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (18, 1, 'El Marg', 'المرج');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (19, 1, 'Ezbet el Nakhl', 'عزبة النخل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (20, 1, 'Matareya', 'المطرية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (21, 1, 'Maadi', 'المعادى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (22, 1, 'Maasara', 'المعصرة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (23, 1, 'Mokattam', 'المقطم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (24, 1, 'Manyal', 'المنيل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (25, 1, 'Mosky', 'الموسكى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (26, 1, 'Nozha', 'النزهة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (27, 1, 'Waily', 'الوايلى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (28, 1, 'Bab al-Shereia', 'باب الشعرية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (29, 1, 'Bolaq', 'بولاق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (30, 1, 'Garden City', 'جاردن سيتى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (31, 1, 'Hadayek El-Kobba', 'حدائق القبة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (32, 1, 'Helwan', 'حلوان');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (33, 1, 'Dar Al Salam', 'دار السلام');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (34, 1, 'Shubra', 'شبرا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (35, 1, 'Tura', 'طره');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (36, 1, 'Abdeen', 'عابدين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (37, 1, 'Abaseya', 'عباسية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (38, 1, 'Ain Shams', 'عين شمس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (39, 1, 'Nasr City', 'مدينة نصر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (40, 1, 'New Heliopolis', 'مصر الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (41, 1, 'Masr Al Qadima', 'مصر القديمة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (42, 1, 'Mansheya Nasir', 'منشية ناصر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (43, 1, 'Badr City', 'مدينة بدر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (44, 1, 'Obour City', 'مدينة العبور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (45, 1, 'Cairo Downtown', 'وسط البلد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (46, 1, 'Zamalek', 'الزمالك');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (47, 1, 'Kasr El Nile', 'قصر النيل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (48, 1, 'Rehab', 'الرحاب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (49, 1, 'Katameya', 'القطامية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (50, 1, 'Madinty', 'مدينتي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (51, 1, 'Rod Alfarag', 'روض الفرج');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (52, 1, 'Sheraton', 'شيراتون');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (53, 1, 'El-Gamaleya', 'الجمالية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (54, 1, '10th of Ramadan City', 'العاشر من رمضان');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (55, 1, 'Helmeyat Alzaytoun', 'الحلمية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (56, 1, 'New Nozha', 'النزهة الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (57, 1, 'Capital New', 'العاصمة الإدارية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (58, 2, 'Giza', 'الجيزة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (59, 2, 'Sixth of October', 'السادس من أكتوبر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (60, 2, 'Cheikh Zayed', 'الشيخ زايد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (61, 2, 'Hawamdiyah', 'الحوامدية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (62, 2, 'Al Badrasheen', 'البدرشين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (63, 2, 'Saf', 'الصف');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (64, 2, 'Atfih', 'أطفيح');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (65, 2, 'Al Ayat', 'العياط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (66, 2, 'Al-Bawaiti', 'الباويطي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (67, 2, 'Manshiyet Al Qanater', 'منشأة القناطر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (68, 2, 'Oaseem', 'أوسيم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (69, 2, 'Kerdasa', 'كرداسة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (70, 2, 'Abu Nomros', 'أبو النمرس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (71, 2, 'Kafr Ghati', 'كفر غطاطي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (72, 2, 'Manshiyet Al Bakari', 'منشأة البكاري');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (73, 2, 'Dokki', 'الدقى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (74, 2, 'Agouza', 'العجوزة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (75, 2, 'Haram', 'الهرم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (76, 2, 'Warraq', 'الوراق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (77, 2, 'Imbaba', 'امبابة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (78, 2, 'Boulaq Dakrour', 'بولاق الدكرور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (79, 2, 'Al Wahat Al Baharia', 'الواحات البحرية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (80, 2, 'Omraneya', 'العمرانية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (81, 2, 'Moneeb', 'المنيب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (82, 2, 'Bin Alsarayat', 'بين السرايات');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (83, 2, 'Kit Kat', 'الكيت كات');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (84, 2, 'Mohandessin', 'المهندسين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (85, 2, 'Faisal', 'فيصل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (86, 2, 'Abu Rawash', 'أبو رواش');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (87, 2, 'Hadayek Alahram', 'حدائق الأهرام');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (88, 2, 'Haraneya', 'الحرانية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (89, 2, 'Hadayek October', 'حدائق اكتوبر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (90, 2, 'Saft Allaban', 'صفط اللبن');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (91, 2, 'Smart Village', 'القرية الذكية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (92, 2, 'Ard Ellwaa', 'ارض اللواء');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (93, 3, 'Abu Qir', 'ابو قير');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (94, 3, 'Al Ibrahimeyah', 'الابراهيمية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (95, 3, 'Azarita', 'الأزاريطة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (96, 3, 'Anfoushi', 'الانفوشى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (97, 3, 'Dekheila', 'الدخيلة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (98, 3, 'El Soyof', 'السيوف');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (99, 3, 'Ameria', 'العامرية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (100, 3, 'El Labban', 'اللبان');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (101, 3, 'Al Mafrouza', 'المفروزة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (102, 3, 'El Montaza', 'المنتزه');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (103, 3, 'Mansheya', 'المنشية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (104, 3, 'Naseria', 'الناصرية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (105, 3, 'Ambrozo', 'امبروزو');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (106, 3, 'Bab Sharq', 'باب شرق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (107, 3, 'Bourj Alarab', 'برج العرب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (108, 3, 'Stanley', 'ستانلى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (109, 3, 'Smouha', 'سموحة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (110, 3, 'Sidi Bishr', 'سيدى بشر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (111, 3, 'Shads', 'شدس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (112, 3, 'Gheet Alenab', 'غيط العنب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (113, 3, 'Fleming', 'فلمينج');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (114, 3, 'Victoria', 'فيكتوريا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (115, 3, 'Camp Shizar', 'كامب شيزار');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (116, 3, 'Karmooz', 'كرموز');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (117, 3, 'Mahta Alraml', 'محطة الرمل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (118, 3, 'Mina El-Basal', 'مينا البصل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (119, 3, 'Asafra', 'العصافرة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (120, 3, 'Agamy', 'العجمي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (121, 3, 'Bakos', 'بكوس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (122, 3, 'Boulkly', 'بولكلي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (123, 3, 'Cleopatra', 'كليوباترا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (124, 3, 'Glim', 'جليم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (125, 3, 'Al Mamurah', 'المعمورة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (126, 3, 'Al Mandara', 'المندرة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (127, 3, 'Moharam Bek', 'محرم بك');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (128, 3, 'Elshatby', 'الشاطبي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (129, 3, 'Sidi Gaber', 'سيدي جابر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (130, 3, 'North Coast/Sahel', 'الساحل الشمالي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (131, 3, 'Alhadra', 'الحضرة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (132, 3, 'Alattarin', 'العطارين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (133, 3, 'Sidi Kerir', 'سيدي كرير');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (134, 3, 'Elgomrok', 'الجمرك');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (135, 3, 'Al Max', 'المكس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (136, 3, 'Marina', 'مارينا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (137, 4, 'Mansoura', 'المنصورة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (138, 4, 'Talkha', 'طلخا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (139, 4, 'Mitt Ghamr', 'ميت غمر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (140, 4, 'Dekernes', 'دكرنس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (141, 4, 'Aga', 'أجا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (142, 4, 'Menia El Nasr', 'منية النصر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (143, 4, 'Sinbillawin', 'السنبلاوين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (144, 4, 'El Kurdi', 'الكردي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (145, 4, 'Bani Ubaid', 'بني عبيد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (146, 4, 'Al Manzala', 'المنزلة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (147, 4, 'Tami al-Amdid', 'تمي الأمديد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (148, 4, 'Aljamalia', 'الجمالية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (149, 4, 'Sherbin', 'شربين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (150, 4, 'Mataria', 'المطرية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (151, 4, 'Belqas', 'بلقاس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (152, 4, 'Meet Salsil', 'ميت سلسيل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (153, 4, 'Gamasa', 'جمصة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (154, 4, 'Mahalat Damana', 'محلة دمنة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (155, 4, 'Nabroh', 'نبروه');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (156, 5, 'Hurghada', 'الغردقة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (157, 5, 'Ras Ghareb', 'رأس غارب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (158, 5, 'Safaga', 'سفاجا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (159, 5, 'El Qusiar', 'القصير');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (160, 5, 'Marsa Alam', 'مرسى علم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (161, 5, 'Shalatin', 'الشلاتين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (162, 5, 'Halaib', 'حلايب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (163, 5, 'Aldahar', 'الدهار');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (164, 6, 'Damanhour', 'دمنهور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (165, 6, 'Kafr El Dawar', 'كفر الدوار');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (166, 6, 'Rashid', 'رشيد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (167, 6, 'Edco', 'إدكو');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (168, 6, 'Abu al-Matamir', 'أبو المطامير');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (169, 6, 'Abu Homs', 'أبو حمص');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (170, 6, 'Delengat', 'الدلنجات');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (171, 6, 'Mahmoudiyah', 'المحمودية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (172, 6, 'Rahmaniyah', 'الرحمانية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (173, 6, 'Itai Baroud', 'إيتاي البارود');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (174, 6, 'Housh Eissa', 'حوش عيسى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (175, 6, 'Shubrakhit', 'شبراخيت');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (176, 6, 'Kom Hamada', 'كوم حمادة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (177, 6, 'Badr', 'بدر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (178, 6, 'Wadi Natrun', 'وادي النطرون');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (179, 6, 'New Nubaria', 'النوبارية الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (180, 6, 'Alnoubareya', 'النوبارية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (181, 7, 'Fayoum', 'الفيوم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (182, 7, 'Fayoum El Gedida', 'الفيوم الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (183, 7, 'Tamiya', 'طامية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (184, 7, 'Snores', 'سنورس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (185, 7, 'Etsa', 'إطسا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (186, 7, 'Epschway', 'إبشواي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (187, 7, 'Yusuf El Sediaq', 'يوسف الصديق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (188, 7, 'Hadqa', 'الحادقة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (189, 7, 'Atsa', 'اطسا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (190, 7, 'Algamaa', 'الجامعة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (191, 7, 'Sayala', 'السيالة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (192, 8, 'Tanta', 'طنطا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (193, 8, 'Al Mahalla Al Kobra', 'المحلة الكبرى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (194, 8, 'Kafr El Zayat', 'كفر الزيات');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (195, 8, 'Zefta', 'زفتى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (196, 8, 'El Santa', 'السنطة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (197, 8, 'Qutour', 'قطور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (198, 8, 'Basion', 'بسيون');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (199, 8, 'Samannoud', 'سمنود');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (200, 9, 'Ismailia', 'الإسماعيلية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (201, 9, 'Fayed', 'فايد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (202, 9, 'Qantara Sharq', 'القنطرة شرق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (203, 9, 'Qantara Gharb', 'القنطرة غرب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (204, 9, 'El Tal El Kabier', 'التل الكبير');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (205, 9, 'Abu Sawir', 'أبو صوير');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (206, 9, 'Kasasien El Gedida', 'القصاصين الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (207, 9, 'Nefesha', 'نفيشة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (208, 9, 'Sheikh Zayed', 'الشيخ زايد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (209, 10, 'Shbeen El Koom', 'شبين الكوم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (210, 10, 'Sadat City', 'مدينة السادات');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (211, 10, 'Menouf', 'منوف');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (212, 10, 'Sars El-Layan', 'سرس الليان');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (213, 10, 'Ashmon', 'أشمون');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (214, 10, 'Al Bagor', 'الباجور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (215, 10, 'Quesna', 'قويسنا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (216, 10, 'Berkat El Saba', 'بركة السبع');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (217, 10, 'Tala', 'تلا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (218, 10, 'Al Shohada', 'الشهداء');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (219, 11, 'Minya', 'المنيا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (220, 11, 'Minya El Gedida', 'المنيا الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (221, 11, 'El Adwa', 'العدوة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (222, 11, 'Magagha', 'مغاغة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (223, 11, 'Bani Mazar', 'بني مزار');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (224, 11, 'Mattay', 'مطاي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (225, 11, 'Samalut', 'سمالوط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (226, 11, 'Madinat El Fekria', 'المدينة الفكرية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (227, 11, 'Meloy', 'ملوي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (228, 11, 'Deir Mawas', 'دير مواس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (229, 11, 'Abu Qurqas', 'ابو قرقاص');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (230, 11, 'Ard Sultan', 'ارض سلطان');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (231, 12, 'Banha', 'بنها');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (232, 12, 'Qalyub', 'قليوب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (233, 12, 'Shubra Al Khaimah', 'شبرا الخيمة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (234, 12, 'Al Qanater Charity', 'القناطر الخيرية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (235, 12, 'Khanka', 'الخانكة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (236, 12, 'Kafr Shukr', 'كفر شكر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (237, 12, 'Tukh', 'طوخ');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (238, 12, 'Qaha', 'قها');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (239, 12, 'Obour', 'العبور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (240, 12, 'Khosous', 'الخصوص');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (241, 12, 'Shibin Al Qanater', 'شبين القناطر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (242, 12, 'Mostorod', 'مسطرد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (243, 13, 'El Kharga', 'الخارجة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (244, 13, 'Paris', 'باريس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (245, 13, 'Mout', 'موط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (246, 13, 'Farafra', 'الفرافرة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (247, 13, 'Balat', 'بلاط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (248, 13, 'Dakhla', 'الداخلة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (249, 14, 'Suez', 'السويس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (250, 14, 'Alganayen', 'الجناين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (251, 14, 'Ataqah', 'عتاقة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (252, 14, 'Ain Sokhna', 'العين السخنة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (253, 14, 'Faysal', 'فيصل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (254, 15, 'Aswan', 'أسوان');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (255, 15, 'Aswan El Gedida', 'أسوان الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (256, 15, 'Drau', 'دراو');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (257, 15, 'Kom Ombo', 'كوم أمبو');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (258, 15, 'Nasr Al Nuba', 'نصر النوبة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (259, 15, 'Kalabsha', 'كلابشة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (260, 15, 'Edfu', 'إدفو');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (261, 15, 'Al-Radisiyah', 'الرديسية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (262, 15, 'Al Basilia', 'البصيلية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (263, 15, 'Al Sibaeia', 'السباعية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (264, 15, 'Abo Simbl Al Siyahia', 'ابوسمبل السياحية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (265, 15, 'Marsa Alam', 'مرسى علم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (266, 16, 'Assiut', 'أسيوط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (267, 16, 'Assiut El Gedida', 'أسيوط الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (268, 16, 'Dayrout', 'ديروط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (269, 16, 'Manfalut', 'منفلوط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (270, 16, 'Qusiya', 'القوصية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (271, 16, 'Abnoub', 'أبنوب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (272, 16, 'Abu Tig', 'أبو تيج');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (273, 16, 'El Ghanaim', 'الغنايم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (274, 16, 'Sahel Selim', 'ساحل سليم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (275, 16, 'El Badari', 'البداري');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (276, 16, 'Sidfa', 'صدفا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (277, 17, 'Bani Sweif', 'بني سويف');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (278, 17, 'Beni Suef El Gedida', 'بني سويف الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (279, 17, 'Al Wasta', 'الواسطى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (280, 17, 'Naser', 'ناصر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (281, 17, 'Ehnasia', 'إهناسيا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (282, 17, 'Beba', 'ببا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (283, 17, 'Fashn', 'الفشن');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (284, 17, 'Somasta', 'سمسطا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (285, 17, 'Alabbaseri', 'الاباصيرى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (286, 17, 'Mokbel', 'مقبل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (287, 18, 'Port Said', 'بورسعيد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (288, 18, 'Port Fouad', 'بورفؤاد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (289, 18, 'Alarab', 'العرب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (290, 18, 'Zohour', 'حى الزهور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (291, 18, 'Alsharq', 'حى الشرق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (292, 18, 'Aldawahi', 'حى الضواحى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (293, 18, 'Almanakh', 'حى المناخ');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (294, 18, 'Mubarak', 'حى مبارك');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (295, 19, 'Damietta', 'دمياط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (296, 19, 'New Damietta', 'دمياط الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (297, 19, 'Ras El Bar', 'رأس البر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (298, 19, 'Faraskour', 'فارسكور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (299, 19, 'Zarqa', 'الزرقا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (300, 19, 'Alsaru', 'السرو');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (301, 19, 'Alruwda', 'الروضة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (302, 19, 'Kafr El-Batikh', 'كفر البطيخ');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (303, 19, 'Azbet Al Burg', 'عزبة البرج');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (304, 19, 'Meet Abou Ghalib', 'ميت أبو غالب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (305, 19, 'Kafr Saad', 'كفر سعد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (306, 20, 'Zagazig', 'الزقازيق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (307, 20, 'Al Ashr Men Ramadan', 'العاشر من رمضان');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (308, 20, 'Minya Al Qamh', 'منيا القمح');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (309, 20, 'Belbeis', 'بلبيس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (310, 20, 'Mashtoul El Souq', 'مشتول السوق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (311, 20, 'Qenaiat', 'القنايات');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (312, 20, 'Abu Hammad', 'أبو حماد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (313, 20, 'El Qurain', 'القرين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (314, 20, 'Hehia', 'ههيا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (315, 20, 'Abu Kabir', 'أبو كبير');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (316, 20, 'Faccus', 'فاقوس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (317, 20, 'El Salihia El Gedida', 'الصالحية الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (318, 20, 'Al Ibrahimiyah', 'الإبراهيمية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (319, 20, 'Deirb Negm', 'ديرب نجم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (320, 20, 'Kafr Saqr', 'كفر صقر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (321, 20, 'Awlad Saqr', 'أولاد صقر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (322, 20, 'Husseiniya', 'الحسينية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (323, 20, 'San Alhajar Alqablia', 'صان الحجر القبلية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (324, 20, 'Manshayat Abu Omar', 'منشأة أبو عمر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (325, 21, 'Al Toor', 'الطور');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (326, 21, 'Sharm El-Shaikh', 'شرم الشيخ');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (327, 21, 'Dahab', 'دهب');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (328, 21, 'Nuweiba', 'نويبع');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (329, 21, 'Taba', 'طابا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (330, 21, 'Saint Catherine', 'سانت كاترين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (331, 21, 'Abu Redis', 'أبو رديس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (332, 21, 'Abu Zenaima', 'أبو زنيمة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (333, 21, 'Ras Sidr', 'رأس سدر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (334, 22, 'Kafr El Sheikh', 'كفر الشيخ');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (335, 22, 'Kafr El Sheikh Downtown', 'وسط البلد كفر الشيخ');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (336, 22, 'Desouq', 'دسوق');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (337, 22, 'Fooh', 'فوه');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (338, 22, 'Metobas', 'مطوبس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (339, 22, 'Burg Al Burullus', 'برج البرلس');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (340, 22, 'Baltim', 'بلطيم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (341, 22, 'Masief Baltim', 'مصيف بلطيم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (342, 22, 'Hamol', 'الحامول');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (343, 22, 'Bella', 'بيلا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (344, 22, 'Riyadh', 'الرياض');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (345, 22, 'Sidi Salm', 'سيدي سالم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (346, 22, 'Qellen', 'قلين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (347, 22, 'Sidi Ghazi', 'سيدي غازي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (348, 23, 'Marsa Matrouh', 'مرسى مطروح');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (349, 23, 'El Hamam', 'الحمام');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (350, 23, 'Alamein', 'العلمين');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (351, 23, 'Dabaa', 'الضبعة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (352, 23, 'Al-Nagila', 'النجيلة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (353, 23, 'Sidi Brani', 'سيدي براني');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (354, 23, 'Salloum', 'السلوم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (355, 23, 'Siwa', 'سيوة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (356, 23, 'Marina', 'مارينا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (357, 23, 'North Coast', 'الساحل الشمالى');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (358, 24, 'Luxor', 'الأقصر');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (359, 24, 'New Luxor', 'الأقصر الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (360, 24, 'Esna', 'إسنا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (361, 24, 'New Tiba', 'طيبة الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (362, 24, 'Al Ziynia', 'الزينية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (363, 24, 'Al Bayadieh', 'البياضية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (364, 24, 'Al Qarna', 'القرنة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (365, 24, 'Armant', 'أرمنت');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (366, 24, 'Al Tud', 'الطود');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (367, 25, 'Qena', 'قنا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (368, 25, 'New Qena', 'قنا الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (369, 25, 'Abu Tesht', 'ابو طشت');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (370, 25, 'Nag Hammadi', 'نجع حمادي');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (371, 25, 'Deshna', 'دشنا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (372, 25, 'Alwaqf', 'الوقف');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (373, 25, 'Qaft', 'قفط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (374, 25, 'Naqada', 'نقادة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (375, 25, 'Farshout', 'فرشوط');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (376, 25, 'Quos', 'قوص');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (377, 26, 'Arish', 'العريش');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (378, 26, 'Sheikh Zowaid', 'الشيخ زويد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (379, 26, 'Nakhl', 'نخل');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (380, 26, 'Rafah', 'رفح');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (381, 26, 'Bir al-Abed', 'بئر العبد');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (382, 26, 'Al Hasana', 'الحسنة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (383, 27, 'Sohag', 'سوهاج');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (384, 27, 'Sohag El Gedida', 'سوهاج الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (385, 27, 'Akhmeem', 'أخميم');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (386, 27, 'Akhmim El Gedida', 'أخميم الجديدة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (387, 27, 'Albalina', 'البلينا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (388, 27, 'El Maragha', 'المراغة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (389, 27, 'Almunshaa', 'المنشأة');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (390, 27, 'Dar AISalaam', 'دار السلام');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (391, 27, 'Gerga', 'جرجا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (392, 27, 'Jahina Al Gharbia', 'جهينة الغربية');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (393, 27, 'Saqilatuh', 'ساقلته');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (394, 27, 'Tama', 'طما');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (395, 27, 'Tahta', 'طهطا');
INSERT INTO cities (id, governorate_id, name_en, name_ar) VALUES (396, 27, 'Alkawthar', 'الكوثر');
